In [3]:
import numpy as np

In [6]:
np.arange(30, 70)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69])

In [7]:
np.arange(30, 70, 2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.random.rand(1)

array([0.94451782])

In [23]:
np.random.seed(2)
a = np.random.randint(0, 100, (5, 5))
a.T
np.linalg.det(a)
np.linalg.inv(a)

array([[-0.01817041,  0.00597883,  0.01971354, -0.01833695, -0.00101178],
       [-0.01244873, -0.00528017,  0.01359428,  0.00663304, -0.00845011],
       [-0.00526662, -0.01676279,  0.01979192, -0.00148126, -0.0037179 ],
       [-0.01703952, -0.01903324, -0.00222043,  0.01932127,  0.02767594],
       [ 0.06203751,  0.03408608, -0.05508429,  0.00733872, -0.00404555]])

In [27]:
eigenvalues, eigenvectors = np.linalg.eig(a)
print(eigenvalues)
print(eigenvectors)

[242.82286842 +0.j         -25.53390121 +0.j
  10.5004722 +31.16148232j  10.5004722 -31.16148232j
  36.71008838 +0.j        ]
[[-0.3804288 +0.j          0.4206635 +0.j         -0.23895879-0.07353505j
  -0.23895879+0.07353505j -0.4413092 +0.j        ]
 [-0.39147391+0.j         -0.11470362+0.j          0.01266919+0.41602273j
   0.01266919-0.41602273j  0.18890313+0.j        ]
 [-0.66566932+0.j         -0.03271399+0.j          0.13907297+0.09706146j
   0.13907297-0.09706146j -0.30944965+0.j        ]
 [-0.36109063+0.j          0.45193351+0.j          0.6520657 +0.j
   0.6520657 -0.j          0.81807776+0.j        ]
 [-0.35849688+0.j         -0.77754176+0.j         -0.35367684-0.43036807j
  -0.35367684+0.43036807j  0.06746478+0.j        ]]


In [28]:
np.linalg.matrix_rank(a)

np.int64(5)

In [29]:
a.trace()

np.int64(275)

In [31]:
a = np.random.randint(1, 10, 10)
b = np.random.randint(1, 10, 10)
a * b

array([54, 42, 28,  7,  4, 27, 27, 18, 15, 63], dtype=int32)

In [32]:
np.random.seed(2)
a = np.random.randint(0, 100, (3, 3))
np.linalg.svd(a)

SVDResult(U=array([[-0.5922343 , -0.05285448, -0.80403043],
       [-0.63732565, -0.57982775,  0.50755866],
       [-0.4930259 ,  0.81302287,  0.30970836]]), S=array([140.09430235,  55.58113996,  13.42845224]), Vh=array([[-0.53312289, -0.28366392, -0.79706635],
       [ 0.82953184, -0.36045051, -0.42655873],
       [ 0.16630365,  0.88860014, -0.42747267]]))

In [34]:
np.linalg.matrix_power(a, 50)

array([[-1080065224,  1659543059,   168803618],
       [ -875679256,   531963617,   870908374],
       [ 1103962176,   883113896,  1926814832]], dtype=int32)