In [1]:
import numpy as np

### 13

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

### 14

In [5]:
np.arange(30, 71)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

### 15

In [7]:
np.arange(30, 71, 2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

### 16

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 17

In [11]:
np.random.rand(10)

array([0.42631727, 0.10695671, 0.46984705, 0.23921728, 0.08578876,
       0.76428019, 0.20740579, 0.30850673, 0.12780293, 0.12509052])

In [12]:
np.random.random((10,))

array([0.26789088, 0.32759869, 0.93055747, 0.52121969, 0.41571516,
       0.9464759 , 0.23908514, 0.58016653, 0.42590088, 0.58898285])

### linalg

In [15]:
np.random.seed(2)
a = np.random.randint(0, 100, (5, 5))
a

array([[40, 15, 72, 22, 43],
       [82, 75,  7, 34, 49],
       [95, 75, 85, 47, 63],
       [31, 90, 20, 37, 39],
       [67,  4, 42, 51, 38]], dtype=int32)

In [17]:
a.T

array([[40, 82, 95, 31, 67],
       [15, 75, 75, 90,  4],
       [72,  7, 85, 20, 42],
       [22, 34, 47, 37, 51],
       [43, 49, 63, 39, 38]], dtype=int32)

In [19]:
np.linalg.det(a)

np.float64(-246114696.00000066)

In [20]:
np.linalg.inv(a)

array([[-0.01817041,  0.00597883,  0.01971354, -0.01833695, -0.00101178],
       [-0.01244873, -0.00528017,  0.01359428,  0.00663304, -0.00845011],
       [-0.00526662, -0.01676279,  0.01979192, -0.00148126, -0.0037179 ],
       [-0.01703952, -0.01903324, -0.00222043,  0.01932127,  0.02767594],
       [ 0.06203751,  0.03408608, -0.05508429,  0.00733872, -0.00404555]])

In [21]:
values, vectors = np.linalg.eig(a)

In [22]:
values

array([242.82286842 +0.j        , -25.53390121 +0.j        ,
        10.5004722 +31.16148232j,  10.5004722 -31.16148232j,
        36.71008838 +0.j        ])

In [25]:
values.prod()

np.complex128(-246114696.00000075+9.401936492633743e-10j)

In [26]:
values.sum()

np.complex128(275+0j)

In [27]:
a.trace()

np.int64(275)

In [23]:
vectors

array([[-0.3804288 +0.j        ,  0.4206635 +0.j        ,
        -0.23895879-0.07353505j, -0.23895879+0.07353505j,
        -0.4413092 +0.j        ],
       [-0.39147391+0.j        , -0.11470362+0.j        ,
         0.01266919+0.41602273j,  0.01266919-0.41602273j,
         0.18890313+0.j        ],
       [-0.66566932+0.j        , -0.03271399+0.j        ,
         0.13907297+0.09706146j,  0.13907297-0.09706146j,
        -0.30944965+0.j        ],
       [-0.36109063+0.j        ,  0.45193351+0.j        ,
         0.6520657 +0.j        ,  0.6520657 -0.j        ,
         0.81807776+0.j        ],
       [-0.35849688+0.j        , -0.77754176+0.j        ,
        -0.35367684-0.43036807j, -0.35367684+0.43036807j,
         0.06746478+0.j        ]])

In [24]:
np.linalg.matrix_rank(a)

np.int64(5)

### 59`

In [28]:
a = np.random.randint(1, 10, 10)
b = np.random.randint(1, 10, 10)

In [29]:
a, b

(array([2, 4, 6, 9, 5, 7, 4, 3, 1, 5], dtype=int32),
 array([3, 5, 2, 8, 9, 3, 9, 8, 2, 7], dtype=int32))

In [30]:
a * b

array([ 6, 20, 12, 72, 45, 21, 36, 24,  2, 35], dtype=int32)

In [31]:
np.random.seed(2)
a = np.random.randint(0, 100, (3, 3))
a

array([[40, 15, 72],
       [22, 43, 82],
       [75,  7, 34]], dtype=int32)

In [32]:
np.linalg.svd(a)

SVDResult(U=array([[-0.5922343 , -0.05285448, -0.80403043],
       [-0.63732565, -0.57982775,  0.50755866],
       [-0.4930259 ,  0.81302287,  0.30970836]]), S=array([140.09430235,  55.58113996,  13.42845224]), Vh=array([[-0.53312289, -0.28366392, -0.79706635],
       [ 0.82953184, -0.36045051, -0.42655873],
       [ 0.16630365,  0.88860014, -0.42747267]]))

In [33]:
a + 5

array([[45, 20, 77],
       [27, 48, 87],
       [80, 12, 39]], dtype=int32)

In [36]:
np.linalg.matrix_power(a, 50)

array([[-1080065224,  1659543059,   168803618],
       [ -875679256,   531963617,   870908374],
       [ 1103962176,   883113896,  1926814832]], dtype=int32)

In [37]:
class M:
    def __init__(self, mat):
        self.mat = mat

    def __matmul__(self, other):
        return M(self.mat @ other.mat)

In [38]:
m1 = M(np.random.randint(1, 10, (3, 3)))
m2 = M(np.random.randint(1, 10, (3, 3)))

In [40]:
m1.mat

array([[2, 6, 5],
       [5, 6, 8],
       [4, 7, 5]], dtype=int32)

In [41]:
m2.mat

array([[4, 8, 7],
       [2, 4, 6],
       [9, 5, 7]], dtype=int32)

In [43]:
m3 = m1 @ m2

In [44]:
m3.mat

array([[ 65,  65,  85],
       [104, 104, 127],
       [ 75,  85, 105]], dtype=int32)